WIP: Implement interactive move
YaLTeR/niri pull request #547
Opened 2024-07-15 18:15 UTC by Pajn

I've started working on interactive move support as I eventually want #122 but it's a little too big to start with. Interactive move feels smaller but still like a step towards it.

Still very wip and not really reviewable except for super high level "the approach is not at all what I want" or similar. Mostly letting people know I'm trying to get it done.

Currently implemented:
- [x] Can pickup with Mod+MouseLeft
- [x] Windows follow cursor after pickup
- [x] Can drop as both new columns and in existing columns using the same 1/3 rule as interactive resize

Not yet implemented:
- [ ] Dragging to different monitors (or workspaces)
- [ ] Some visual indication of where you'll drop
- [ ] Some way to scroll workspaces while dragging
- [ ] Animations and rerenders needs some more love

2024-07-15 18:17 UTC, YaLTeR commented
Cool! But just FYI, I was going to get this done as part of adding floating windows, which will need lots of refactoring.

2024-07-15 18:20 UTC, YaLTeR commented
(I am postponing it until then specifically because it will influence the architecture and design of moving windows)

2024-07-15 18:21 UTC, Pajn commented
@YaLTeR If you are on it I can drop it. I wanted to try and get a feel for the code before committing to something publicly but do understand that it can mean it doesn't at all fit with your plans or is already started in some other way.

2024-07-15 18:27 UTC, YaLTeR commented
I am not "on it" (busy with uni atm, don't want to take on big tasks for the time being), but it will likely lead to different design and code compared to implementing move without a floating layer. For example, I thought that moving a window out of a column would just put it on the floating layer for the duration of the move (and then whether it stays there or goes back into a column depends on where you drop it). Which is obviously not possible without a floating layer. Or, how to handle moves across monitors, which will also be just transparently handled by the floating layer, etc.

2024-07-15 18:51 UTC, Pajn commented
That was badly worded. Having some thoughts about the implementation definately counts in what I inteded with "on it" even if not actively or having started coding. And you should ofc. prio uni.
I'm very happy to just drop it if you want. Or rework it in a way closer to what you describe.
I'm thinking maybe I could take a shot at adding a "floating layer" that to start with will only be used for holding the window under drag and then full floating support can be added to it later?
However that would immediately raise at the very least one architectural question that maybe you don't want to nail down atm. Is the floating layer bound to a workspace (so floating windows are hidden when you switch workspace/possibly other floating windows from the new workspace are shown) or is the floating layer above the workspace so the same floating windows are shown over all workspaces?

2024-07-15 19:01 UTC, YaLTeR commented
> However that would immediately raise at the very least one architectural question that maybe you don't want to nail down atm. Is the floating layer bound to a workspace (so floating windows are hidden when you switch workspace/possibly other floating windows from the new workspace are shown) or is the floating layer above the workspace so the same floating windows are shown over all workspaces?

I think floating should be global across monitors (use the same coordinate system as the mouse pointer essentially) and, for the first impl, always on top (no workspaces). This means, among other things, moving monitor position tracking into the layout.

> I'm very happy to just drop it if you want. Or rework it in a way closer to what you describe.
>
> I'm thinking maybe I could take a shot at adding a "floating layer" that to start with will only be used for holding the window under drag and then full floating support can be added to it later?

Well, I really don't want to tell people to drop something, especially when I haven't started working on it myself. I took a very brief glance at the contents of this PR and it seems to change all the expected places, which is good. But it's just, with larger refactors like this, it may turn out that reviewing someone else's work and shaping it to my vision takes way more effort for both parties than if I eventually just do a several day long dive myself.

2024-07-15 21:45 UTC, Pajn commented
>But it's just, with larger refactors like this, it may turn out that reviewing someone else's work and shaping it to my vision takes way more effort for both parties than if I eventually just do a several day long dive myself.

Totally agree and why not tackling floating layout directly and also why I'm happy to drop this work if you think it's too close to it. I'll start looking into shaping this into something that could work well with the floating layout you describe and see if it's possible while keeping it small.

2024-07-18 09:54 UTC, Pajn commented
I've reworked it to remove the window from the workspace and store it on layout during the move instead. So while no floating layer atm. I think it should work pretty well with one, with some code just getting moved into it instead.

So far it has been very kind to the existing structure but I do start to need to extract some stuff from Tile into some kind of TopLevel structure that can be used by both Tile and the moving window (as well as floating windows in the future). For example borders and the rendering logic.

Still very wip and not ready for review but I'm at a point where its very usable for myself at least.
I tried to make it autoscroll to show the insert hint but that part feels quite yanky to use. Probably just going to drop it and add a way to manually scroll the workspace during the move.

2024-07-18 10:19 UTC, YaLTeR commented
> I do start to need to extract some stuff from Tile into some kind of TopLevel structure that can be used by both Tile and the moving window (as well as floating windows in the future)

That is what the Tile already is. Window with borders and other stuff. Don't mind that it's called Tile.

2024-07-22 09:35 UTC, Pajn commented
I think this is working quite well now.

- Switched to using Tile which cleaned up a few things and added back focus-ring rendering
- Switched the attempt at auto-scrolling to instead allow pressing the middle mouse button during the move for manual scrolling.
- Tested workspace and output actions during moving and made sure it doesn't blow up

2024-07-23 05:27 UTC, YaLTeR commented
I'll try to take a look over the following days.

2024-07-28 07:00 UTC, YaLTeR requested changes
Thanks, this looks very solid already!

These clients are very useful for testing: https://gitlab.freedesktop.org/emersion/wleird

Especially wleird-resize-loop. I also found useful these patches to it:
```diff
diff --git a/resize-loop.c b/resize-loop.c
index c1171a5..200908f 100644
--- a/resize-loop.c
+++ b/resize-loop.c
@@ -6,7 +6,7 @@
 
 #define MIN 2
 #define MAX 512
-#define SPEED 10
+#define SPEED 3
 static int size = MIN;
 
 static struct wleird_toplevel toplevel = {0};
@@ -27,6 +27,8 @@ static void callback_handle_done(void *data, struct wl_callback *callback,
 
 	toplevel.surface.width = abs(size);
 	toplevel.surface.height = abs(size);
+	xdg_toplevel_set_min_size(toplevel.xdg_toplevel, abs(size), abs(size));
+	xdg_toplevel_set_max_size(toplevel.xdg_toplevel, abs(size), abs(size));
 	surface_render(&toplevel.surface);
 
 	size += SPEED;
```

2024-07-28 07:00 UTC, YaLTeR commented on src/layout/workspace.rs
> +                if column_index == 0 || column_index == self.columns.len() {
Hint at index 0 is rendered one gap further to the right than it should be (so it touches the next window).

2024-07-28 07:14 UTC, Pajn commented on src/window/mapped.rs
> +    /// Used for double-move-click tracking.
Right, I copied the setup from resize without thinking about that. Nothing probably makes sense for now at least. It still allows adding maximize or other things later.

2024-09-07 16:10 UTC, v3xro commented
This now needs to be rebased to remove the gradient changes that were force-pushed to main.

2024-09-30 06:02 UTC, YaLTeR commented
Do you mind if I finish this PR myself?

2024-09-30 07:21 UTC, Pajn commented
Sorry that I've been so slow in picking this up again. Of course feel free to finish it!

2024-09-30 07:24 UTC, YaLTeR commented
Alright, no worries! I'll try to get to it sometime in the next days.

2024-10-07 14:57 UTC, YaLTeR commented
Could you please allow me to edit this PR's branch by checking this checkbox at the bottom of the right panel:

![image](https://github.com/user-attachments/assets/92246f9e-e58f-4a33-b693-22386a944d25)

2024-10-07 15:06 UTC, Pajn commented
Right, sorry, enabled now

2024-10-07 17:46 UTC, YaLTeR commented
Fascinating. Seems like our `Op` enum got large enough to trigger a stack overflow in proptest-derive's generated code: https://github.com/proptest-rs/proptest/issues/152

Thankfully, they have a feature to work around the problem.

2024-10-22 09:16 UTC, YaLTeR commented
Alright, I think I did more or less everything I wanted before merging. The rest can happen later.

Going to test this a bit to see if any more bugs or weirdness shows up (anyone following along, feel free to help with the testing) and then merge.

2024-10-23 06:15 UTC, regenman commented
Tried the PR, with particular focus on touchscreen interaction - it works well on my 2-in-1, with one notable exception: Alacritty doesn't seem to react at all on touch events on the CSD/borders. I wonder if that's simply missing in their implementation? [The alacritty issue for touch support](https://github.com/alacritty/alacritty/issues/3671#issuecomment-855428699) hints that this might be the case, but I can't really tell if it was finally left out in the implementation.

2024-10-23 06:16 UTC, YaLTeR commented
> Alacritty doesn't seem to react at all on touch events on the CSD/borders. I wonder if that's simply missing in their implementation?

Yes, or likely from https://github.com/PolyMeilex/sctk-adwaita which is where the CSD bar comes from.

2024-10-28 06:07 UTC, merged