Add a window swap operation
YaLTeR/niri pull request #899
Opened 2024-12-27 16:33 UTC by rustn00b

Swap the active window in the active column with a neighboring column's active window.

This PR adds a `swap-window-left` and `swap-window-right` action. They are used to swap the active window
in the active column with the active window in a neighboring column. When there is no neighboring column it
behaves just like the respective `expel-window-....` actions.

This is something quite simple but that I often found missing when using Niri. It was standard in Awesome and easy enough to script in Sway, but I was unable to create a decent niri-ipc based version.

2024-12-27 16:37 UTC, YaLTeR commented
Interesting, what do you use this for?

2024-12-27 16:46 UTC, rustn00b commented
> Interesting, what do you use this for?

I usually have a column of things I'm working on in the context of some project or other (say 3-5 windows), and to the side a column with a single window (or maybe 2). The work happens in the single "master" window, and I swap the windows into this "master" position based on what needs doing.

What I like about this approach is that it keeps a set of windows available as a palette of sorts, while also affording
decent screen real estate to the current area of focus. But there might be smarter ways of going about it ;)

2025-01-02 15:15 UTC, YaLTeR requested changes
Also don't forget to run `cargo +nightly fmt`.

2025-01-02 15:15 UTC, YaLTeR commented on src/layout/scrolling.rs
> +        let adjusted_target_column_idx =
I'd make `target_column_idx` mutable and `-= 1` it.

2025-01-02 15:15 UTC, YaLTeR commented on src/layout/mod.rs
> +    pub fn swap_window_in_direction(&mut self, direction: ScrollDirection) {
Please add this to the `Op` test enum below so it can participate in randomized tests.

2025-01-03 14:43 UTC, rustn00b commented on src/layout/scrolling.rs
> +        let adjusted_target_column_idx =
ah, but I still need the original `target_column_idx` further along. The `adjusted_target_column_idx` is only meaningful during the code window where the source column may have been removed and has not yet been recreated.
I added an explicit block to make this more obvious.

2025-01-05 07:57 UTC, YaLTeR requested changes
Rebased and fixed two small issues. Could you address these two remaining ones?

2025-01-05 07:57 UTC, YaLTeR commented on src/layout/scrolling.rs
> +        // to an `consume_or_expel_window_left` (resp. `consume_or_expel_window_right`)
Should it be? Upon my initial testing, it feels weird that swap-window will preserve the number of tiles in a column, except when you do it towards an empty spot, at which point it'll break (you can't swap-window it back into a column).

Maybe in this case this should just do nothing?

2025-01-05 07:57 UTC, YaLTeR commented on src/layout/scrolling.rs
> +        // Animations
The animation for the target tile is a little broken: it jumps vertically. This should be fixed.

2025-01-05 13:31 UTC, rustn00b commented on src/layout/scrolling.rs
> +        // to an `consume_or_expel_window_left` (resp. `consume_or_expel_window_right`)
Valid point, as I was putting this together I debated with myself over this one and went with the "swap with an empty column is an expel" approach. But I also found it weird that you couldn't reverse an unintended action by just swapping in the opposite direction. So I'll just make it a no-op instead.

2025-01-09 08:29 UTC, merged

2025-01-09 08:37 UTC, YaLTeR commented
Thanks!